services:
  postgres:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: fileEnc
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    networks:
      - fileEnc-network
    restart: unless-stopped

networks:
  fileEnc-network:
    driver: bridge
volumes:
  postgres:
    driver: local